export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";
export const SERVER_CALL_FAILED = "SERVER_CALL_FAILED";
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SERVER_RESPONSE_SUCCESS =
  "SIGNUP_USER_SERVER_RESPONSE_SUCCESS";
export const SIGNUP_USER_SERVER_RESPONSE_ERROR =
  "SIGNUP_USER_SERVER_RESPONSE_ERROR";
